/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsAdvisorRouteImport } from './routes/tools/advisor'
import { Route as ResearchSezLandscape2026RouteImport } from './routes/research.sez-landscape-2026'
import { Route as FrameworkStageIdRouteImport } from './routes/framework/$stageId'
import { Route as AuthStartRouteImport } from './routes/auth/start'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminStagesRouteImport } from './routes/admin.stages'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAdvisorRoute = ToolsAdvisorRouteImport.update({
  id: '/tools/advisor',
  path: '/tools/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSezLandscape2026Route =
  ResearchSezLandscape2026RouteImport.update({
    id: '/sez-landscape-2026',
    path: '/sez-landscape-2026',
    getParentRoute: () => ResearchRoute,
  } as any)
const FrameworkStageIdRoute = FrameworkStageIdRouteImport.update({
  id: '/framework/$stageId',
  path: '/framework/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStagesRoute = AdminStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/admin/stages': typeof AdminStagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/framework/$stageId': typeof FrameworkStageIdRoute
  '/research/sez-landscape-2026': typeof ResearchSezLandscape2026Route
  '/tools/advisor': typeof ToolsAdvisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/admin/stages': typeof AdminStagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/framework/$stageId': typeof FrameworkStageIdRoute
  '/research/sez-landscape-2026': typeof ResearchSezLandscape2026Route
  '/tools/advisor': typeof ToolsAdvisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/admin/stages': typeof AdminStagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/framework/$stageId': typeof FrameworkStageIdRoute
  '/research/sez-landscape-2026': typeof ResearchSezLandscape2026Route
  '/tools/advisor': typeof ToolsAdvisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/map'
    | '/methodology'
    | '/news'
    | '/profile'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/admin/stages'
    | '/auth/callback'
    | '/auth/start'
    | '/framework/$stageId'
    | '/research/sez-landscape-2026'
    | '/tools/advisor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/map'
    | '/methodology'
    | '/news'
    | '/profile'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/admin/stages'
    | '/auth/callback'
    | '/auth/start'
    | '/framework/$stageId'
    | '/research/sez-landscape-2026'
    | '/tools/advisor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/map'
    | '/methodology'
    | '/news'
    | '/profile'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/admin/stages'
    | '/auth/callback'
    | '/auth/start'
    | '/framework/$stageId'
    | '/research/sez-landscape-2026'
    | '/tools/advisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TrackerRoute: typeof TrackerRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStartRoute: typeof AuthStartRoute
  FrameworkStageIdRoute: typeof FrameworkStageIdRoute
  ToolsAdvisorRoute: typeof ToolsAdvisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/advisor': {
      id: '/tools/advisor'
      path: '/tools/advisor'
      fullPath: '/tools/advisor'
      preLoaderRoute: typeof ToolsAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/sez-landscape-2026': {
      id: '/research/sez-landscape-2026'
      path: '/sez-landscape-2026'
      fullPath: '/research/sez-landscape-2026'
      preLoaderRoute: typeof ResearchSezLandscape2026RouteImport
      parentRoute: typeof ResearchRoute
    }
    '/framework/$stageId': {
      id: '/framework/$stageId'
      path: '/framework/$stageId'
      fullPath: '/framework/$stageId'
      preLoaderRoute: typeof FrameworkStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stages': {
      id: '/admin/stages'
      path: '/stages'
      fullPath: '/admin/stages'
      preLoaderRoute: typeof AdminStagesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminStagesRoute: typeof AdminStagesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStagesRoute: AdminStagesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResearchRouteChildren {
  ResearchSezLandscape2026Route: typeof ResearchSezLandscape2026Route
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSezLandscape2026Route: ResearchSezLandscape2026Route,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TrackerRoute: TrackerRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStartRoute: AuthStartRoute,
  FrameworkStageIdRoute: FrameworkStageIdRoute,
  ToolsAdvisorRoute: ToolsAdvisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
