/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as CmIndexRouteImport } from './routes/cm/index'
import { Route as ToolsAdvisorRouteImport } from './routes/tools/advisor'
import { Route as ResearchSezLandscape2026RouteImport } from './routes/research.sez-landscape-2026'
import { Route as FrameworkStageIdRouteImport } from './routes/framework/$stageId'
import { Route as CmSubmittalRouteImport } from './routes/cm/submittal'
import { Route as CmSiteDiaryRouteImport } from './routes/cm/site-diary'
import { Route as CmSettingsRouteImport } from './routes/cm/settings'
import { Route as CmScheduleRouteImport } from './routes/cm/schedule'
import { Route as CmSafetyRouteImport } from './routes/cm/safety'
import { Route as CmRolePermissionsRouteImport } from './routes/cm/role-permissions'
import { Route as CmReportsRouteImport } from './routes/cm/reports'
import { Route as CmPunchListRouteImport } from './routes/cm/punch-list'
import { Route as CmPhotosRouteImport } from './routes/cm/photos'
import { Route as CmManpowerRouteImport } from './routes/cm/manpower'
import { Route as CmInspectionRouteImport } from './routes/cm/inspection'
import { Route as CmEquipmentRouteImport } from './routes/cm/equipment'
import { Route as CmDirectoryRouteImport } from './routes/cm/directory'
import { Route as CmDashboardRouteImport } from './routes/cm/dashboard'
import { Route as CmBoqRouteImport } from './routes/cm/boq'
import { Route as CmProjectIdRouteImport } from './routes/cm/$projectId'
import { Route as AuthStartRouteImport } from './routes/auth/start'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminStagesRouteImport } from './routes/admin.stages'
import { Route as CmProjectsIndexRouteImport } from './routes/cm/projects/index'
import { Route as CmJoinTokenRouteImport } from './routes/cm/join/$token'
import { Route as CmAuthCallbackRouteImport } from './routes/cm/auth/callback'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchRoute,
} as any)
const CmIndexRoute = CmIndexRouteImport.update({
  id: '/cm/',
  path: '/cm/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAdvisorRoute = ToolsAdvisorRouteImport.update({
  id: '/tools/advisor',
  path: '/tools/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSezLandscape2026Route =
  ResearchSezLandscape2026RouteImport.update({
    id: '/sez-landscape-2026',
    path: '/sez-landscape-2026',
    getParentRoute: () => ResearchRoute,
  } as any)
const FrameworkStageIdRoute = FrameworkStageIdRouteImport.update({
  id: '/framework/$stageId',
  path: '/framework/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const CmSubmittalRoute = CmSubmittalRouteImport.update({
  id: '/cm/submittal',
  path: '/cm/submittal',
  getParentRoute: () => rootRouteImport,
} as any)
const CmSiteDiaryRoute = CmSiteDiaryRouteImport.update({
  id: '/cm/site-diary',
  path: '/cm/site-diary',
  getParentRoute: () => rootRouteImport,
} as any)
const CmSettingsRoute = CmSettingsRouteImport.update({
  id: '/cm/settings',
  path: '/cm/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CmScheduleRoute = CmScheduleRouteImport.update({
  id: '/cm/schedule',
  path: '/cm/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const CmSafetyRoute = CmSafetyRouteImport.update({
  id: '/cm/safety',
  path: '/cm/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CmRolePermissionsRoute = CmRolePermissionsRouteImport.update({
  id: '/cm/role-permissions',
  path: '/cm/role-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CmReportsRoute = CmReportsRouteImport.update({
  id: '/cm/reports',
  path: '/cm/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CmPunchListRoute = CmPunchListRouteImport.update({
  id: '/cm/punch-list',
  path: '/cm/punch-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CmPhotosRoute = CmPhotosRouteImport.update({
  id: '/cm/photos',
  path: '/cm/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const CmManpowerRoute = CmManpowerRouteImport.update({
  id: '/cm/manpower',
  path: '/cm/manpower',
  getParentRoute: () => rootRouteImport,
} as any)
const CmInspectionRoute = CmInspectionRouteImport.update({
  id: '/cm/inspection',
  path: '/cm/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const CmEquipmentRoute = CmEquipmentRouteImport.update({
  id: '/cm/equipment',
  path: '/cm/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const CmDirectoryRoute = CmDirectoryRouteImport.update({
  id: '/cm/directory',
  path: '/cm/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const CmDashboardRoute = CmDashboardRouteImport.update({
  id: '/cm/dashboard',
  path: '/cm/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CmBoqRoute = CmBoqRouteImport.update({
  id: '/cm/boq',
  path: '/cm/boq',
  getParentRoute: () => rootRouteImport,
} as any)
const CmProjectIdRoute = CmProjectIdRouteImport.update({
  id: '/cm/$projectId',
  path: '/cm/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStagesRoute = AdminStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => AdminRoute,
} as any)
const CmProjectsIndexRoute = CmProjectsIndexRouteImport.update({
  id: '/cm/projects/',
  path: '/cm/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmJoinTokenRoute = CmJoinTokenRouteImport.update({
  id: '/cm/join/$token',
  path: '/cm/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CmAuthCallbackRoute = CmAuthCallbackRouteImport.update({
  id: '/cm/auth/callback',
  path: '/cm/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/admin/stages': typeof AdminStagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/cm/$projectId': typeof CmProjectIdRoute
  '/cm/boq': typeof CmBoqRoute
  '/cm/dashboard': typeof CmDashboardRoute
  '/cm/directory': typeof CmDirectoryRoute
  '/cm/equipment': typeof CmEquipmentRoute
  '/cm/inspection': typeof CmInspectionRoute
  '/cm/manpower': typeof CmManpowerRoute
  '/cm/photos': typeof CmPhotosRoute
  '/cm/punch-list': typeof CmPunchListRoute
  '/cm/reports': typeof CmReportsRoute
  '/cm/role-permissions': typeof CmRolePermissionsRoute
  '/cm/safety': typeof CmSafetyRoute
  '/cm/schedule': typeof CmScheduleRoute
  '/cm/settings': typeof CmSettingsRoute
  '/cm/site-diary': typeof CmSiteDiaryRoute
  '/cm/submittal': typeof CmSubmittalRoute
  '/framework/$stageId': typeof FrameworkStageIdRoute
  '/research/sez-landscape-2026': typeof ResearchSezLandscape2026Route
  '/tools/advisor': typeof ToolsAdvisorRoute
  '/cm/': typeof CmIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/cm/auth/callback': typeof CmAuthCallbackRoute
  '/cm/join/$token': typeof CmJoinTokenRoute
  '/cm/projects/': typeof CmProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/admin/stages': typeof AdminStagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/cm/$projectId': typeof CmProjectIdRoute
  '/cm/boq': typeof CmBoqRoute
  '/cm/dashboard': typeof CmDashboardRoute
  '/cm/directory': typeof CmDirectoryRoute
  '/cm/equipment': typeof CmEquipmentRoute
  '/cm/inspection': typeof CmInspectionRoute
  '/cm/manpower': typeof CmManpowerRoute
  '/cm/photos': typeof CmPhotosRoute
  '/cm/punch-list': typeof CmPunchListRoute
  '/cm/reports': typeof CmReportsRoute
  '/cm/role-permissions': typeof CmRolePermissionsRoute
  '/cm/safety': typeof CmSafetyRoute
  '/cm/schedule': typeof CmScheduleRoute
  '/cm/settings': typeof CmSettingsRoute
  '/cm/site-diary': typeof CmSiteDiaryRoute
  '/cm/submittal': typeof CmSubmittalRoute
  '/framework/$stageId': typeof FrameworkStageIdRoute
  '/research/sez-landscape-2026': typeof ResearchSezLandscape2026Route
  '/tools/advisor': typeof ToolsAdvisorRoute
  '/cm': typeof CmIndexRoute
  '/research': typeof ResearchIndexRoute
  '/cm/auth/callback': typeof CmAuthCallbackRoute
  '/cm/join/$token': typeof CmJoinTokenRoute
  '/cm/projects': typeof CmProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/admin/stages': typeof AdminStagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/cm/$projectId': typeof CmProjectIdRoute
  '/cm/boq': typeof CmBoqRoute
  '/cm/dashboard': typeof CmDashboardRoute
  '/cm/directory': typeof CmDirectoryRoute
  '/cm/equipment': typeof CmEquipmentRoute
  '/cm/inspection': typeof CmInspectionRoute
  '/cm/manpower': typeof CmManpowerRoute
  '/cm/photos': typeof CmPhotosRoute
  '/cm/punch-list': typeof CmPunchListRoute
  '/cm/reports': typeof CmReportsRoute
  '/cm/role-permissions': typeof CmRolePermissionsRoute
  '/cm/safety': typeof CmSafetyRoute
  '/cm/schedule': typeof CmScheduleRoute
  '/cm/settings': typeof CmSettingsRoute
  '/cm/site-diary': typeof CmSiteDiaryRoute
  '/cm/submittal': typeof CmSubmittalRoute
  '/framework/$stageId': typeof FrameworkStageIdRoute
  '/research/sez-landscape-2026': typeof ResearchSezLandscape2026Route
  '/tools/advisor': typeof ToolsAdvisorRoute
  '/cm/': typeof CmIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/cm/auth/callback': typeof CmAuthCallbackRoute
  '/cm/join/$token': typeof CmJoinTokenRoute
  '/cm/projects/': typeof CmProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/map'
    | '/methodology'
    | '/news'
    | '/profile'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/admin/stages'
    | '/auth/callback'
    | '/auth/start'
    | '/cm/$projectId'
    | '/cm/boq'
    | '/cm/dashboard'
    | '/cm/directory'
    | '/cm/equipment'
    | '/cm/inspection'
    | '/cm/manpower'
    | '/cm/photos'
    | '/cm/punch-list'
    | '/cm/reports'
    | '/cm/role-permissions'
    | '/cm/safety'
    | '/cm/schedule'
    | '/cm/settings'
    | '/cm/site-diary'
    | '/cm/submittal'
    | '/framework/$stageId'
    | '/research/sez-landscape-2026'
    | '/tools/advisor'
    | '/cm/'
    | '/research/'
    | '/cm/auth/callback'
    | '/cm/join/$token'
    | '/cm/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/map'
    | '/methodology'
    | '/news'
    | '/profile'
    | '/settings'
    | '/tracker'
    | '/admin/stages'
    | '/auth/callback'
    | '/auth/start'
    | '/cm/$projectId'
    | '/cm/boq'
    | '/cm/dashboard'
    | '/cm/directory'
    | '/cm/equipment'
    | '/cm/inspection'
    | '/cm/manpower'
    | '/cm/photos'
    | '/cm/punch-list'
    | '/cm/reports'
    | '/cm/role-permissions'
    | '/cm/safety'
    | '/cm/schedule'
    | '/cm/settings'
    | '/cm/site-diary'
    | '/cm/submittal'
    | '/framework/$stageId'
    | '/research/sez-landscape-2026'
    | '/tools/advisor'
    | '/cm'
    | '/research'
    | '/cm/auth/callback'
    | '/cm/join/$token'
    | '/cm/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/map'
    | '/methodology'
    | '/news'
    | '/profile'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/admin/stages'
    | '/auth/callback'
    | '/auth/start'
    | '/cm/$projectId'
    | '/cm/boq'
    | '/cm/dashboard'
    | '/cm/directory'
    | '/cm/equipment'
    | '/cm/inspection'
    | '/cm/manpower'
    | '/cm/photos'
    | '/cm/punch-list'
    | '/cm/reports'
    | '/cm/role-permissions'
    | '/cm/safety'
    | '/cm/schedule'
    | '/cm/settings'
    | '/cm/site-diary'
    | '/cm/submittal'
    | '/framework/$stageId'
    | '/research/sez-landscape-2026'
    | '/tools/advisor'
    | '/cm/'
    | '/research/'
    | '/cm/auth/callback'
    | '/cm/join/$token'
    | '/cm/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TrackerRoute: typeof TrackerRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStartRoute: typeof AuthStartRoute
  CmProjectIdRoute: typeof CmProjectIdRoute
  CmBoqRoute: typeof CmBoqRoute
  CmDashboardRoute: typeof CmDashboardRoute
  CmDirectoryRoute: typeof CmDirectoryRoute
  CmEquipmentRoute: typeof CmEquipmentRoute
  CmInspectionRoute: typeof CmInspectionRoute
  CmManpowerRoute: typeof CmManpowerRoute
  CmPhotosRoute: typeof CmPhotosRoute
  CmPunchListRoute: typeof CmPunchListRoute
  CmReportsRoute: typeof CmReportsRoute
  CmRolePermissionsRoute: typeof CmRolePermissionsRoute
  CmSafetyRoute: typeof CmSafetyRoute
  CmScheduleRoute: typeof CmScheduleRoute
  CmSettingsRoute: typeof CmSettingsRoute
  CmSiteDiaryRoute: typeof CmSiteDiaryRoute
  CmSubmittalRoute: typeof CmSubmittalRoute
  FrameworkStageIdRoute: typeof FrameworkStageIdRoute
  ToolsAdvisorRoute: typeof ToolsAdvisorRoute
  CmIndexRoute: typeof CmIndexRoute
  CmAuthCallbackRoute: typeof CmAuthCallbackRoute
  CmJoinTokenRoute: typeof CmJoinTokenRoute
  CmProjectsIndexRoute: typeof CmProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/cm/': {
      id: '/cm/'
      path: '/cm'
      fullPath: '/cm/'
      preLoaderRoute: typeof CmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/advisor': {
      id: '/tools/advisor'
      path: '/tools/advisor'
      fullPath: '/tools/advisor'
      preLoaderRoute: typeof ToolsAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/sez-landscape-2026': {
      id: '/research/sez-landscape-2026'
      path: '/sez-landscape-2026'
      fullPath: '/research/sez-landscape-2026'
      preLoaderRoute: typeof ResearchSezLandscape2026RouteImport
      parentRoute: typeof ResearchRoute
    }
    '/framework/$stageId': {
      id: '/framework/$stageId'
      path: '/framework/$stageId'
      fullPath: '/framework/$stageId'
      preLoaderRoute: typeof FrameworkStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/submittal': {
      id: '/cm/submittal'
      path: '/cm/submittal'
      fullPath: '/cm/submittal'
      preLoaderRoute: typeof CmSubmittalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/site-diary': {
      id: '/cm/site-diary'
      path: '/cm/site-diary'
      fullPath: '/cm/site-diary'
      preLoaderRoute: typeof CmSiteDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/settings': {
      id: '/cm/settings'
      path: '/cm/settings'
      fullPath: '/cm/settings'
      preLoaderRoute: typeof CmSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/schedule': {
      id: '/cm/schedule'
      path: '/cm/schedule'
      fullPath: '/cm/schedule'
      preLoaderRoute: typeof CmScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/safety': {
      id: '/cm/safety'
      path: '/cm/safety'
      fullPath: '/cm/safety'
      preLoaderRoute: typeof CmSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/role-permissions': {
      id: '/cm/role-permissions'
      path: '/cm/role-permissions'
      fullPath: '/cm/role-permissions'
      preLoaderRoute: typeof CmRolePermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/reports': {
      id: '/cm/reports'
      path: '/cm/reports'
      fullPath: '/cm/reports'
      preLoaderRoute: typeof CmReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/punch-list': {
      id: '/cm/punch-list'
      path: '/cm/punch-list'
      fullPath: '/cm/punch-list'
      preLoaderRoute: typeof CmPunchListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/photos': {
      id: '/cm/photos'
      path: '/cm/photos'
      fullPath: '/cm/photos'
      preLoaderRoute: typeof CmPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/manpower': {
      id: '/cm/manpower'
      path: '/cm/manpower'
      fullPath: '/cm/manpower'
      preLoaderRoute: typeof CmManpowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/inspection': {
      id: '/cm/inspection'
      path: '/cm/inspection'
      fullPath: '/cm/inspection'
      preLoaderRoute: typeof CmInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/equipment': {
      id: '/cm/equipment'
      path: '/cm/equipment'
      fullPath: '/cm/equipment'
      preLoaderRoute: typeof CmEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/directory': {
      id: '/cm/directory'
      path: '/cm/directory'
      fullPath: '/cm/directory'
      preLoaderRoute: typeof CmDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/dashboard': {
      id: '/cm/dashboard'
      path: '/cm/dashboard'
      fullPath: '/cm/dashboard'
      preLoaderRoute: typeof CmDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/boq': {
      id: '/cm/boq'
      path: '/cm/boq'
      fullPath: '/cm/boq'
      preLoaderRoute: typeof CmBoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/$projectId': {
      id: '/cm/$projectId'
      path: '/cm/$projectId'
      fullPath: '/cm/$projectId'
      preLoaderRoute: typeof CmProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stages': {
      id: '/admin/stages'
      path: '/stages'
      fullPath: '/admin/stages'
      preLoaderRoute: typeof AdminStagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cm/projects/': {
      id: '/cm/projects/'
      path: '/cm/projects'
      fullPath: '/cm/projects/'
      preLoaderRoute: typeof CmProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/join/$token': {
      id: '/cm/join/$token'
      path: '/cm/join/$token'
      fullPath: '/cm/join/$token'
      preLoaderRoute: typeof CmJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/auth/callback': {
      id: '/cm/auth/callback'
      path: '/cm/auth/callback'
      fullPath: '/cm/auth/callback'
      preLoaderRoute: typeof CmAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminStagesRoute: typeof AdminStagesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStagesRoute: AdminStagesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResearchRouteChildren {
  ResearchSezLandscape2026Route: typeof ResearchSezLandscape2026Route
  ResearchIndexRoute: typeof ResearchIndexRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSezLandscape2026Route: ResearchSezLandscape2026Route,
  ResearchIndexRoute: ResearchIndexRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TrackerRoute: TrackerRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStartRoute: AuthStartRoute,
  CmProjectIdRoute: CmProjectIdRoute,
  CmBoqRoute: CmBoqRoute,
  CmDashboardRoute: CmDashboardRoute,
  CmDirectoryRoute: CmDirectoryRoute,
  CmEquipmentRoute: CmEquipmentRoute,
  CmInspectionRoute: CmInspectionRoute,
  CmManpowerRoute: CmManpowerRoute,
  CmPhotosRoute: CmPhotosRoute,
  CmPunchListRoute: CmPunchListRoute,
  CmReportsRoute: CmReportsRoute,
  CmRolePermissionsRoute: CmRolePermissionsRoute,
  CmSafetyRoute: CmSafetyRoute,
  CmScheduleRoute: CmScheduleRoute,
  CmSettingsRoute: CmSettingsRoute,
  CmSiteDiaryRoute: CmSiteDiaryRoute,
  CmSubmittalRoute: CmSubmittalRoute,
  FrameworkStageIdRoute: FrameworkStageIdRoute,
  ToolsAdvisorRoute: ToolsAdvisorRoute,
  CmIndexRoute: CmIndexRoute,
  CmAuthCallbackRoute: CmAuthCallbackRoute,
  CmJoinTokenRoute: CmJoinTokenRoute,
  CmProjectsIndexRoute: CmProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
